import { test, expect } from '@playwright/test';
import { login, noHorizontalOverflow } from './helpers';

test('mobile library and editor remain usable without horizontal overflow', async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await login(page);
  await page.getByRole('navigation', { name: '모바일 메뉴' }).getByRole('button', { name: '전체 앨범', exact: true }).click();
  await page.locator('.album-card').filter({ has: page.getByRole('heading', { name: '제주 여행', exact: true }) }).click();
  await expect(page.locator('.album-header h1')).toContainText('제주 여행');
  await noHorizontalOverflow(page);
  await page.getByRole('navigation', { name: '모바일 메뉴' }).getByRole('button', { name: '내 사진', exact: true }).click();
  await expect(page.locator('.library-heading h2')).toContainText('지수님이 나온 사진');
  await page.locator('.filter-pills').getByRole('button', { name: '혼자', exact: true }).click();
  await expect(page.locator('.photo-card').first()).toBeVisible();
  await noHorizontalOverflow(page);
  await page.screenshot({ path: testInfo.outputPath('mobile-library.png'), fullPage: true });
  await testInfo.attach('Mobile library', { path: testInfo.outputPath('mobile-library.png'), contentType: 'image/png' });
  await page.locator('.photo-open').first().click();
  const editor = page.getByRole('dialog', { name: '사진 보정 및 함께 고르기' });
  await expect(editor).toBeVisible();
  await expect(editor.getByRole('slider', { name: '밝기' })).toBeVisible();
  await editor.getByRole('slider', { name: '밝기' }).press('ArrowRight');
  await editor.getByRole('button', { name: '슬라이더로 비교' }).click();
  await expect(editor.getByRole('slider', { name: '원본과 보정본 비교 위치' })).toBeVisible();
  await noHorizontalOverflow(page);
  await page.screenshot({ path: testInfo.outputPath('mobile-editor.png') });
  await testInfo.attach('Mobile editor image', { path: testInfo.outputPath('mobile-editor.png'), contentType: 'image/png' });
  await editor.getByRole('slider', { name: '밝기' }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: testInfo.outputPath('mobile-editor-controls.png') });
  await testInfo.attach('Mobile editor controls', { path: testInfo.outputPath('mobile-editor-controls.png'), contentType: 'image/png' });
  await editor.getByRole('button', { name: '사진 상세 닫기' }).click();
  await expect(editor).not.toBeVisible();
  await page.getByRole('button', { name: '사진 올리기', exact: true }).first().click();
  await expect(page.getByRole('dialog', { name: '사진 올리기' })).toBeVisible();
  await noHorizontalOverflow(page);
  await page.getByRole('dialog').getByRole('button', { name: '닫기', exact: true }).click();
  await page.getByRole('button', { name: '앨범 설정', exact: true }).click();
  const settings = page.getByRole('dialog', { name: '앨범 설정', exact: true });
  await expect(settings.getByLabel('앨범 이름', { exact: true })).toHaveValue('제주 여행');
  await expect(settings.getByRole('combobox', { name: '여행 시간대', exact: true })).toBeVisible();
  await noHorizontalOverflow(page);
  await page.screenshot({ path: testInfo.outputPath('mobile-album-settings.png') });
  await testInfo.attach('Mobile album settings', { path: testInfo.outputPath('mobile-album-settings.png'), contentType: 'image/png' });
  await settings.getByRole('button', { name: '닫기', exact: true }).click();
  await page.getByRole('button', { name: '사진 정리 현황', exact: true }).click();
  const analysis = page.getByRole('dialog', { name: '사진 정리 현황', exact: true });
  await expect(analysis).toContainText('샘플 사진 분석 모드');
  await expect(analysis.getByLabel('분석 상태별 사진 수')).toBeVisible();
  await expect(analysis.getByRole('button', { name: '닫기', exact: true })).toBeInViewport();
  await noHorizontalOverflow(page);
  await page.screenshot({ path: testInfo.outputPath('mobile-analysis-status.png') });
  await testInfo.attach('Mobile analysis status', { path: testInfo.outputPath('mobile-analysis-status.png'), contentType: 'image/png' });
  await analysis.getByRole('button', { name: '닫기', exact: true }).click();
  await page.getByRole('navigation', { name: '모바일 메뉴' }).getByRole('button', { name: '전체 앨범', exact: true }).click();
  await expect(page.locator('.album-cards')).toBeVisible();
  await noHorizontalOverflow(page);
  expect(errors).toEqual([]);
});
